### ISSUE TITLE
Error in command 'botstats toggle'. Check your console or logs for details.

### ISSUE THREAD

**Issue by XxPoNaGeXx** [NekoTony/Neko-Cogs#9]
Exception in command 'botstats toggle'
Traceback (most recent call last):
  File "lib/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/bot/Gayming Bot/cogs/botstats.py", line 38, in toggle
    await self.botstatz()
  File "/home/bot/Gayming Bot/cogs/botstats.py", line 94, in botstatz
    await self.bot.change_presence(game=game, status=status)
  File "lib/discord/client.py", line 1934, in change_presence
    yield from self.ws.change_presence(game=game, status=status, afk=afk)
  File "lib/discord/gateway.py", line 477, in change_presence
    yield from self.send(sent)
  File "lib/discord/gateway.py", line 442, in send
    yield from super().send(data)
  File "lib/websockets/protocol.py", line 310, in send
    yield from self.ensure_open()
  File "lib/websockets/protocol.py", line 394, in ensure_open
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1001, no reason.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "lib/discord/ext/commands/bot.py", line 846, in process_commands
    yield from command.invoke(ctx)
  File "lib/discord/ext/commands/core.py", line 634, in invoke
    yield from ctx.invoked_subcommand.invoke(ctx)
  File "lib/discord/ext/commands/core.py", line 374, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "lib/discord/ext/commands/core.py", line 54, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: ConnectionClosed: WebSocket connection is closed: code = 1001, no reason.

**Comment by NekoTony** [comment]
Not sure this is a problem with the code itself but discord.

**Comment by NekoTony** [comment]
Which os?

**Comment by XxPoNaGeXx** [comment]
Debian, it just randomly outputted into my bot management channel 

http://i.imgur.com/v7G9VNz.png

**Comment by NekoTony** [comment]
Error not on the code end.
